# Always validate the PR title AND all the commits
titleAndCommits: true

# Allow use of Merge commits.
allowMergeCommits: true

scopes:
  - all
  - credentials
  - crossrefs
  - graph
  - grbac
  - hub
  - iam
  - image
  - knowledge
  - library
  - multimedia
  - product
  - release
  - resourcemanager
  - tracker
  - vision
  - webcache
  - webpage

types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
