name: Animeshon APIs [cleanup]

env:
  EMAIL: ${{ secrets.WORKFLOW_GITHUB_EMAIL }}
  USERNAME: ${{ secrets.WORKFLOW_GITHUB_USERNAME }}
  TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

on:
  delete:

jobs:
  branch-delete:
    runs-on: ubuntu-latest

    steps:
    - name: Clone animeapis/proto-binary
      uses: actions/checkout@v2
      with:
        repository: animeapis/proto-binary
        path: animeapis/proto-binary
        token: ${{ env.TOKEN }}

    - name: Clone animeapis/api-go-client
      uses: actions/checkout@v2
      with:
        repository: animeapis/api-go-client
        path: animeapis/api-go-client
        token: ${{ env.TOKEN }}

    - name: Clone animeapis/go-genproto
      uses: actions/checkout@v2
      with:
        repository: animeapis/go-genproto
        path: animeapis/go-genproto
        token: ${{ env.TOKEN }}

    # - name: Clone animeapis/api-nodejs-client
    #   uses: actions/checkout@v2
    #   with:
    #     repository: animeapis/api-nodejs-client
    #     path: animeapis/api-nodejs-client
    #     token: ${{ env.TOKEN }}

    - name: Clone animeapis/openapi-specification
      uses: actions/checkout@v2
      with:
        repository: animeapis/openapi-specification
        path: animeapis/openapi-specification
        token: ${{ env.TOKEN }}

    - name: Clone animeapis/graphql-schema
      uses: actions/checkout@v2
      with:
        repository: animeapis/graphql-schema
        path: animeapis/graphql-schema
        token: ${{ env.TOKEN }}

    - name: Clone animeapis/reference-markdown
      uses: actions/checkout@v2
      with:
        repository: animeapis/reference-markdown
        path: animeapis/reference-markdown
        token: ${{ env.TOKEN }}

    - name: Delete branch ${{ github.event.ref }} from animeapis/proto-binary
      working-directory: animeapis/proto-binary
      run: |-
        git push origin --delete ${{ github.event.ref }}

    - name: Delete branch ${{ github.event.ref }} from animeapis/api-go-client
      working-directory: animeapis/api-go-client
      run: |-
        git push origin --delete ${{ github.event.ref }}

    - name: Delete branch ${{ github.event.ref }} from animeapis/go-genproto
      working-directory: animeapis/go-genproto
      run: |-
        git push origin --delete ${{ github.event.ref }}

    # - name: Delete branch ${{ github.event.ref }} from animeapis/api-nodejs-client
    #   working-directory: animeapis/api-nodejs-client
    #   run: |-
    #     git push origin --delete ${{ github.event.ref }}

    - name: Delete branch ${{ github.event.ref }} from animeapis/openapi-specification
      working-directory: animeapis/openapi-specification
      run: |-
        git push origin --delete ${{ github.event.ref }}

    - name: Delete branch ${{ github.event.ref }} from animeapis/graphql-schema
      working-directory: animeapis/graphql-schema
      run: |-
        git push origin --delete ${{ github.event.ref }}

    - name: Delete branch ${{ github.event.ref }} from animeapis/reference-markdown
      working-directory: animeapis/reference-markdown
      run: |-
        git push origin --delete ${{ github.event.ref }}
