name: Animeshon APIs

env:
  EMAIL: ${{ secrets.WORKFLOW_GITHUB_EMAIL }}
  USERNAME: ${{ secrets.WORKFLOW_GITHUB_USERNAME }}
  TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone animeapis/animeapis
      uses: actions/checkout@v2

    - name: Clone animeapis/proto-binary
      uses: actions/checkout@v2
      with:
        repository: animeapis/proto-binary
        path: animeapis/proto-binary
        token: ${{ env.TOKEN }}
        ref: ${{ github.ref }}

    - name: Clone animeapis/api-go-client
      uses: actions/checkout@v2
      with:
        repository: animeapis/api-go-client
        path: animeapis/api-go-client
        token: ${{ env.TOKEN }}
        ref: ${{ github.ref }}

    - name: Clone animeapis/go-genproto
      uses: actions/checkout@v2
      with:
        repository: animeapis/go-genproto
        path: animeapis/go-genproto
        token: ${{ env.TOKEN }}
        ref: ${{ github.ref }}

    - name: Cache bazel and bazelisk
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/bazelisk
          ~/.cache/bazel
        key: ${{ runner.os }}-bazel-cache

    - name: Build all client libraries
      run: |-
        bazelisk build //...

    - name: Copy all generated files to their own repositories
      run: |-
        bash .github/workflows/release.sh

    - name: Generate new commit for animeapis/proto-binary
      if: github.ref == 'refs/heads/master'
      working-directory: animeapis/proto-binary
      run: |-
        git config --local user.email "${{ env.EMAIL }}"
        git config --local user.name "${{ env.USERNAME }}"

        git config --local core.filemode false

        git add -A
        git diff-index --quiet HEAD || git commit -m "chore(all): auto-regenerate protobuf binaries"

        git remote set-url origin https://${{ env.USERNAME }}:${{ env.TOKEN }}@github.com/animeapis/proto-binary.git
        git push origin ${{ github.ref }}

    - name: Generate new commit for animeapis/api-go-client
      if: github.ref == 'refs/heads/master'
      working-directory: animeapis/api-go-client
      run: |-
        git config --local user.email "${{ env.EMAIL }}"
        git config --local user.name "${{ env.USERNAME }}"

        git config --local core.filemode false

        git add -A
        git diff-index --quiet HEAD || git commit -m "chore(all): auto-regenerate gapics"

        git remote set-url origin https://${{ env.USERNAME }}:${{ env.TOKEN }}@github.com/animeapis/api-go-client.git
        git push origin ${{ github.ref }}

    - name: Generate new commit for animeapis/go-genproto
      if: github.ref == 'refs/heads/master'
      working-directory: animeapis/go-genproto
      run: |-
        git config --local user.email "${{ env.EMAIL }}"
        git config --local user.name "${{ env.USERNAME }}"

        git config --local core.filemode false

        git add -A
        git diff-index --quiet HEAD || git commit -m "chore(all): auto-regenerate .pb.go files"

        git remote set-url origin https://${{ env.USERNAME }}:${{ env.TOKEN }}@github.com/animeapis/go-genproto.git
        git push origin ${{ github.ref }}
