name: Animeshon APIs

env:
  EMAIL: ${{ secrets.WORKFLOW_GITHUB_EMAIL }}
  USERNAME: ${{ secrets.WORKFLOW_GITHUB_USERNAME }}
  TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone animeapis/animeapis
      uses: actions/checkout@v2

    - name: Clone animeapis/proto-binary
      uses: actions/checkout@v2
      with:
        repository: animeapis/proto-binary
        path: animeapis/proto-binary

    - name: Clone animeapis/api-go-client
      uses: actions/checkout@v2
      with:
        repository: animeapis/api-go-client
        path: animeapis/api-go-client

    - name: Clone animeapis/go-genproto
      uses: actions/checkout@v2
      with:
        repository: animeapis/go-genproto
        path: animeapis/go-genproto

    - name: Cache bazel and bazelisk
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/bazelisk
          ~/.cache/bazel
        key: ${{ runner.os }}-bazel

    - name: Build all client libraries
      run: |-
        bazelisk build //...

    - run: |-
        mkdir -p animeapis/proto-binary/hub/v1alpha1

        # animeapis/proto-binary
        cp bazel-bin/animeshon/hub/v1alpha1/hub_proto_with_info-set.proto.bin animeapis/proto-binary/hub/v1alpha1/hub_with_info.proto.bin
        cp bazel-bin/animeshon/hub/v1alpha1/hub_proto-descriptor-set.proto.bin animeapis/proto-binary/hub/v1alpha1/hub.proto.bin

    - run: |-
        mkdir -p animeapis/api-go-client/hub/v1alpha1

        # animeapis/api-go-client
        cp -r bazel-bin/animeshon/hub/v1alpha1/hub_go_gapic_srcjar_metadata.json/github.com/animeapis .
        cp -r bazel-bin/animeshon/hub/v1alpha1/hub_go_gapic_srcjar_main.go/github.com/animeapis .
        cp -r bazel-bin/animeshon/hub/v1alpha1/hub_go_gapic_srcjar_test.go/github.com/animeapis .

    - run: |-
        mkdir -p animeapis/go-genproto/hub/v1alpha1
        
        # animeapis/go-genproto
        cp -r bazel-bin/animeshon/hub/v1alpha1/hub_go_proto_/github.com/animeapis .

    - name: Setup git environment
      run: |-
        git config --global user.email "${{ env.EMAIL }}"
        git config --global user.name "${{ env.USERNAME }}"

        git config --global core.filemode false

    - name: Generate new commit for animeapis/proto-binary
      working-directory: animeapis/proto-binary
      run: |-
        git add -A
        git diff-index --quiet HEAD || git commit -m "chore(all): auto-regenerate .bin files"

        git remote set-url upstream https://${{ env.USERNAME }}:${{ env.TOKEN }}@github.com/animeapis/proto-binary.git
        git push upstream ${{ github.ref }}

    - name: Generate new commit for animeapis/api-go-client
      working-directory: animeapis/api-go-client
      run: |-
        git add -A
        git diff-index --quiet HEAD || git commit -m "chore(all): auto-regenerate .pb.go files"

        git remote set-url upstream https://${{ env.USERNAME }}:${{ env.TOKEN }}@github.com/animeapis/api-go-client.git
        git push upstream ${{ github.ref }}

    - name: Generate new commit for animeapis/go-genproto
      working-directory: animeapis/go-genproto
      run: |-
        git add -A
        git diff-index --quiet HEAD || git commit -m "chore(all): auto-regenerate gapics"

        git remote set-url upstream https://${{ env.USERNAME }}:${{ env.TOKEN }}@github.com/animeapis/go-genproto.git
        git push upstream ${{ github.ref }}
